name: ft_transcendence

services:
  web:
    build: ./reqs/web
    args:
      ALP_VERSION: ${ALP_VERSION}
    restart: unless-stopped
    depends_on:
      - ruby
    env_file: ".env"
    # IDEA Does the web volume need access to the ruby files? Or the react ones?
    volumes:
       - type: volume
         source: FE_vol
         target: ${FE_FILES}
    networks:
      - app_int
    # NOTE Binds to high host ports so that we can run rootlessly
    # IDEA This may need to change as we get to completion?
    ports:
      - "8080:80"
      - "8443:443"

  db:
    build:
      context: ./reqs/postgres
      args:
        ALP_VERSION: ${ALP_VERSION}
        DB_FILES: ${DB_FILES}
        RB_DBNAME: /run/secrets/RB_DBNAME
        RB_DBUSER: /run/secrets/RB_DBUSER
        WP_DBPASS: /run/secrets/RB_DBPASS
    secrets:
      - RB_DBPASS
      - RB_DBNAME
      - RB_DBUSER
    restart: on-failure:3
    volumes:
      - type: volume
        source: DB_vol
        target: ${DB_FILES}
    networks:
      - app_int
    expose:
      - "5432"
    env_file: ".env"

  ruby:
    build:
      context: ./reqs/ruby
      args:
        ALP_VERSION: ${ALP_VERSION}
        RB_FILES: ${RB_FILES}
        RB_DBHOST: ${RB_DBHOST}
        RB_DBNAME: /run/secrets/RB_DBNAME
        RB_DBUSER: /run/secrets/RB_DBUSER
        RB_DBPASS: /run/secrets/RB_DBPASS
        RUBY_VERSION: ${RUBY_VERSION}
        RUBY_DOWNLOAD_SHA256: ${RUBY_DOWNLOAD_SHA256}
    secrets:
      - RB_DBPASS
      - RB_DBNAME
      - RB_DBUSER
    env_file: ".env"
    depends_on:
      - db
    restart: unless-stopped
    # NOTE Without this it stops immediately. One day I will remember why...
    tty: True
    networks:
      - app_int
    expose:
      - "3000"

# TODO Do we need a location for the ruby files? Other pieces?
volumes:
  DB_vol:

  FE_vol:

  RB_vol:

# NOTE This should point to a folder *outside* of version control!
secrets:
  RB_DBUSER:
    file: ../secret/rb_dbuser
  RB_DBNAME:
    file: ../secret/rb_dbname
  RB_DBPASS:
    file: ../secret/rb_dbpass

# "the presence of these objects is sufficient to define them"
networks:
  app_int:
