services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # WHy are these volumes like this?
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
