server {  listen 80;  server_name _;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl ;
  server_name _;

  http2 on;

  root /usr/share/nginx/html;
  index index.html;

  ssl_certificate     /etc/nginx/ssl/server.crt;
  ssl_certificate_key /etc/nginx/ssl/server.key;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    try_files $uri $uri/ /index.html;
  }
  # Catch /api and proxy to another container (use the container DNS name)
  location ^~ /api/ {
    # container name + port (adjust as needed)
    proxy_pass http://api:3000;
	# TODO Should we be communicating via https with rails?
    #proxy_pass https://api:3000;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    proxy_http_version 1.1;
    proxy_set_header Connection "";

    # We use this because it is a self-signed certificate
    proxy_ssl_verify off;
  }

  # ActionCable
  location ^~ /cable {
    proxy_pass http://api:3000/cable;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
