name: ft_transcendence

services:
  web:
    # FIXME should be depends on api or similar, transient faults if not
    build:
      context: ./frontend
      # NOTE This is one bind mount and one storage volume defined on the fly
    volumes:
      - ../frontend:/app
       - /app/node_modules
    # TODO Ideally this would be binding to 80 but that needs root
    ports:
      - "8080:80"
      - "8443:443"
    env_file:
      - frontend/.env
    depends_on:
      - api
    networks:
      - app_int
    healthcheck:
      test: ["CMD-SHELL","nginx -t"]
      interval: 30s
      timeout: 5s
      retries: 3
  # web_complex:
  #   build:
  #     context: ./frontend
  #     args:
  #       ALP_VERSION: ${ALP_VERSION}
  #   restart: unless-stopped
  #   depends_on:
  #     - ruby
  #   env_file: ".env"
  #   # IDEA Does the web volume need access to the ruby files? Or the react ones?
  #   volumes:
  #      - type: volume
  #        source: FE_vol
  #        target: ${FE_FILES}
  #   networks:
  #     - app_int
  #   # NOTE Binds to high host ports so that we can run rootlessly
  #   # IDEA This may need to change as we get to completion?
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
     # NOTE This is an alternative way to specify healthchecks if they are not in the image

  # TODO This part is formatted different from the others, not ideal.
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/RB_DBPASS
    secrets:
      - RB_DBPASS
    env_file:
      - backend/.env
    volumes:
      - DB_vol:/var/lib/postgresql/data
    networks:
      - app_int
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  api:
    build:
      context: backend
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/RB_DBPASS
      SECRET_42: /run/secrets/42_SECRET

    # Este comando es vital: borra el PID fantasma de Rails y luego arranca el servidor
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # NOTE Bind mount for development
    volumes:
      - ./backend:/app  # <--- LA MAGIA: Sincroniza tu carpeta local con el contenedor
    env_file:
      - backend/.env
    secrets:
      - RB_DBPASS
      - 42_SECRET
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_int
    healthcheck:
      test:
      - "CMD-SHELL"
      - "ruby -e 'require \"net/http\"; u=URI(\"http://localhost:3000/health\");
r=Net::HTTP.get_response(u); exit(r.code.start_with?(\"2\") ? 0 : 1)'"
      interval: 30s
      timeout: 2s
      retries: 20

  # db_complex:
  #   build:
  #     context: ./backend
  #     args:
  #       ALP_VERSION: ${ALP_VERSION}
  #       DB_FILES: ${DB_FILES}
  #       RB_DBNAME: /run/secrets/RB_DBNAME
  #       RB_DBUSER: /run/secrets/RB_DBUSER
  #       WP_DBPASS: /run/secrets/RB_DBPASS
  #   secrets:
  #     - RB_DBPASS
  #     - RB_DBNAME
  #     - RB_DBUSER
  #   restart: on-failure:3
  #   volumes:
  #     - type: volume
  #       source: DB_vol
  #       target: ${DB_FILES}
  #   networks:
  #     - app_int
  #   expose:
  #     - "5432"
  #   env_file: ".env"

 # TODO Do we need a location for the ruby files? Other pieces?
volumes:
  DB_vol:

  FE_vol:

  RB_vol:

# NOTE This should point to a folder *outside* of version control!
secrets:
  RB_DBUSER:
    file: ./secret/rb_dbuser
  RB_DBNAME:
    file: ./secret/rb_dbname
  RB_DBPASS:
    file: ./secret/rb_dbpass
  42_SECRET:
    file: ./secret/42API_SEC

# "the presence of these objects is sufficient to define them"
networks:
  app_int:
