name: ft_transcendence

services:
  web:
    # FIXME should be depends on api or similar,   transient faults if not
    build:
      context: ./frontend
      # NOTE This is one bind mount and one storage volume defined on the fly
      # TODO Work out which of these are actually needed
      args:
        VITE_BASE_URL: ${BASE_URL}
        VITE_42_REDIRECT_URI: ${REDIRECT_URI_42}
        VITE_API_URL: ${VITE_API_URL}
        VITE_CABLE_URL: ${VITE_CABLE_URL}
        VITE_USE_MOCK: ${VITE_USE_MOCK}
        VITE_42_CLIENT_ID: ${UID_42}
    volumes:
      - ../frontend:/app
       - /app/node_modules
    # TODO Ideally this would be binding to 80 but that needs root
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - api
    networks:
      - app_int
    healthcheck:
      test: ["CMD-SHELL","nginx -t"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/RB_DBPASS
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    secrets:
      - RB_DBPASS
    volumes:
      - DB_vol:/var/lib/postgresql/data
    networks:
      - app_int
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  api:
    build:
      context: backend
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    environment:
      BASE_URL: ${BASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/RB_DBPASS
      UID_42: ${UID_42}
      REDIRECT_URI_42: ${REDIRECT_URI_42}
      SECRET_42: /run/secrets/42_SECRET
      SMTP_USER: ${SMTP_USER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PASSWORD: /run/secrets/SMTP_PASS
      SMTP_DOMAIN: ${SMTP_DOMAIN}

    # Este comando es vital: borra el PID fantasma de Rails y luego arranca el servidor
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # NOTE Bind mount for development
    volumes:
      - ./backend:/app  # <--- LA MAGIA: Sincroniza tu carpeta local con el contenedor
    secrets:
      - RB_DBPASS
      - 42_SECRET
      - SMTP_PASS
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_int
    healthcheck:
      test:
      - "CMD-SHELL"
      - "ruby -e 'require \"net/http\"; u=URI(\"http://localhost:3000/health\");
r=Net::HTTP.get_response(u); exit(r.code.start_with?(\"2\") ? 0 : 1)'"
      interval: 30s
      timeout: 2s
      retries: 20

volumes:
  DB_vol:

  FE_vol:

  RB_vol:

# NOTE This should point to a folder *outside* of version control!
secrets:
  RB_DBUSER:
    file: ./secret/rb_dbuser
  RB_DBNAME:
    file: ./secret/rb_dbname
  RB_DBPASS:
    file: ./secret/rb_dbpass
  42_SECRET:
    file: ./secret/42API_SEC
  SMTP_PASS:
    file: ./secret/SMTP_PASS

# "the presence of these objects is sufficient to define them"
networks:
  app_int:
