name: ft_transcendence

services:
  web:
    build:
      context: ./frontend
      # NOTE This is one bind mount and one storage volume defined on the fly
    volumes:
      - ../frontend:/app
       - /app/node_modules
    # TODO Ideally this would be binding to 80 but that needs root
    # TODO Also expand to 443 for HTTPS
    ports:
      - "8080:80"
    env_file:
      - frontend/.env
    networks:
      - app_int
  # web_complex:
  #   build:
  #     context: ./frontend
  #     args:
  #       ALP_VERSION: ${ALP_VERSION}
  #   restart: unless-stopped
  #   depends_on:
  #     - ruby
  #   env_file: ".env"
  #   # IDEA Does the web volume need access to the ruby files? Or the react ones?
  #   volumes:
  #      - type: volume
  #        source: FE_vol
  #        target: ${FE_FILES}
  #   networks:
  #     - app_int
  #   # NOTE Binds to high host ports so that we can run rootlessly
  #   # IDEA This may need to change as we get to completion?
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
  #   # NOTE This is an alternative way to specify healthchecks if they are not in the image
  #   # healthcheck:
  #   #   test: ["CMD-SHELL","nginx -t"]
  #   #   interval: 30s
  #   #   timeout: 5s
  #   #   retries: 3

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/RB_DBPASS
    secrets:
      - RB_DBPASS
    env_file:
      - backend/.env
    volumes:
      - DB_vol:/var/lib/postgresql/data
    # FIXME the note here makes no sense in context
    # ports:
    #   - "5432:5432" # Expone el puerto por si quieres conectarte con DBeaver o pgAdmin
    networks:
      - app_int

  api:
    build:
      context: backend
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/RB_DBPASS
      SECRET_42: /run/secrets/42_SECRET
    # Este comando es vital: borra el PID fantasma de Rails y luego arranca el servidor
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # NOTE Bind mount for development
    volumes:
      - ./backend:/app  # <--- LA MAGIA: Sincroniza tu carpeta local con el contenedor
    # ports:
    #   - "3000:3000"
    env_file:
      - backend/.env
    secrets:
      - RB_DBPASS
      - 42_SECRET
    depends_on:
      - db
    networks:
      - app_int

  # db_complex:
  #   build:
  #     context: ./backend
  #     args:
  #       ALP_VERSION: ${ALP_VERSION}
  #       DB_FILES: ${DB_FILES}
  #       RB_DBNAME: /run/secrets/RB_DBNAME
  #       RB_DBUSER: /run/secrets/RB_DBUSER
  #       WP_DBPASS: /run/secrets/RB_DBPASS
  #   secrets:
  #     - RB_DBPASS
  #     - RB_DBNAME
  #     - RB_DBUSER
  #   restart: on-failure:3
  #   volumes:
  #     - type: volume
  #       source: DB_vol
  #       target: ${DB_FILES}
  #   networks:
  #     - app_int
  #   expose:
  #     - "5432"
  #   env_file: ".env"
  #   # healthcheck:
  #   #   test: ["CMD-SHELL","pg_isready -U postgres || exit 1"]
  #   #   interval: 30s
  #   #   timeout: 5s
  #   #   retries: 3

 # TODO Do we need a location for the ruby files? Other pieces?
volumes:
  DB_vol:

  FE_vol:

  RB_vol:

# NOTE This should point to a folder *outside* of version control!
secrets:
  RB_DBUSER:
    file: ./secret/rb_dbuser
  RB_DBNAME:
    file: ./secret/rb_dbname
  RB_DBPASS:
    file: ./secret/rb_dbpass
  42_SECRET:
    file: ./secret/42API_SEC

# "the presence of these objects is sufficient to define them"
networks:
  app_int:
