# *Deeply* sketchy SSL practice.
# TO be copied to nginx/snippets and include'd in conf file
# Source is a bit random, TODO comment all part of file
# https://www.howtogeek.com/devops/how-to-create-and-use-self-signed-ssl-on-nginx/
# NOTE these 2 lines should be chabnged to match where the files go
ssl_certificate /etc/ssl/certs/inception.crt;
ssl_certificate_key /etc/ssl/private/inception.key;
# Added stronger TLS here
ssl_protocols TLSv1.2 TLSv1.3;

# Do we care about these hardening options? Seems to help
ssl_prefer_server_ciphers on;
ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
ssl_session_timeout 10m;
# this is declared elsewhere
#ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;

# We clearly don't need to staple a homemade certificate
#ssl_stapling on;
# And we even more don't need to ask google if it's OK!
#ssl_stapling_verify on;
#resolver 8.8.8.8 8.8.4.4 valid=300s;
#resolver_timeout 5s;

# These extra headers might be useful but I don't understand them
# and am deeming them out-of-scope today.
# add_header X-Frame-Options DENY;
# add_header X-Content-Type-Options nosniff;
# add_header X-XSS-Protection "1; mode=block";
